name: AppShelliOS
options:
  minimumXcodeGenVersion: 2.44.1
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"

packages:
  WalletAppSwift:
    path: ../../..
  Nuke:
    url: https://github.com/kean/Nuke.git
    from: 12.8.0

targets:
  AppShelliOS:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cpcash.appshell.ios
        GENERATE_INFOPLIST_FILE: YES
        TARGETED_DEVICE_FAMILY: "1,2"
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 0.1.0
        SUPPORTS_MACCATALYST: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
        INFOPLIST_KEY_NSCameraUsageDescription: 扫码转账需要访问相机
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: 选择头像需要访问相册
    dependencies:
      - package: WalletAppSwift
        product: CoreRuntime
      - package: WalletAppSwift
        product: SecurityCore
      - package: WalletAppSwift
        product: BackendAPI
      - package: WalletAppSwift
        product: WebDAppContainer
      - package: WalletAppSwift
        product: NftGalleryModule
      - package: Nuke
        product: NukeUI

  AppShelliOSTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - Tests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: AppShelliOS
      - package: WalletAppSwift
        product: BackendAPI

  AppShelliOSUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - UITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.cpcash.appshell.ios.uitests
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: AppShelliOS

schemes:
  AppShelliOS:
    build:
      targets:
        AppShelliOS: all
        AppShelliOSTests: [test]
        AppShelliOSUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: AppShelliOSTests
        - name: AppShelliOSUITests
